version: '3.8'

services:
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - "80:8000"

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db-mysql
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #
      MYSQL_DATABASE: crud_db
      MYSQL_PASSWORD: 123456

volumes:
  db:
